apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: urbv43lec-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/urbv43lec-java-springboot-gitops